---
title: "HW1"
author: "Jeffrey Brown"
date: "September 21, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

library(readxl)
library(dplyr)
library(ggplot2)
library(colorspace)
library(ggrepel)
library(ggthemes)
library(plotly)
library(htmlwidgets)


```

```{r}
healthyLifeExpectancy <- read_excel('C:/Users/Jeffrey/Desktop/My Documents/Grad School/Classes/Fall 2022/Staa 566/ExpectedHealthyYearsByCountry.xlsx')	
healthyLifeExpectancy <- data.frame(healthyLifeExpectancy)

healthExpenditure <- read_excel('C:/Users/Jeffrey/Desktop/My Documents/Grad School/Classes/Fall 2022/Staa 566/HealthExpenditureByCountry.xlsx')	
healthExpenditure <- data.frame(healthExpenditure)

insuranceType <- read_excel('C:/Users/Jeffrey/Desktop/My Documents/Grad School/Classes/Fall 2022/Staa 566/InsuranceTypeByCountry.xlsx')	
insuranceType <- data.frame(insuranceType)

obesityIndex <- read_excel('C:/Users/Jeffrey/Desktop/My Documents/Grad School/Classes/Fall 2022/Staa 566/ObesityIndexByCountry.xlsx')	
obesityIndex <- data.frame(obesityIndex)


head(healthyLifeExpectancy)
head(healthExpenditure)
head(insuranceType)
head(obesityIndex)


```





```{r}

dfHle <- healthyLifeExpectancy %>% 
  select('Country', 'Year', 'ExpectedHealthyYears') %>%
  filter(Year == 2019)

dfHe <- healthExpenditure %>% 
  select('Country', 'Indicator', 'Y2019') %>%
  filter(Indicator == 'GDP per Capita in US Dollar')

dfHePPP <- healthExpenditure %>% 
  select('Country', 'Indicator', 'Y2019') %>%
  filter(Indicator == 'CHC per Capita in PPP')

dfIt <- insuranceType
dfOi <- obesityIndex

df <- dfHle %>%
              inner_join(dfHe, by='Country') %>%
              inner_join(dfHePPP, by='Country') %>%
              inner_join(dfIt, by='Country') %>%
              inner_join(dfOi, by='Country')
  


colnames(df)[which(names(df) == 'Y2019.x')] <- 'GdpPerCapita'
colnames(df)[which(names(df) == 'Y2019.y')] <- 'PPP'
colnames(df)[which(names(df) == 'ObesityIndex.y')] <- 'ObesityIndex' 
head(df)

df <- df %>% select('Country', 'ExpectedHealthyYears', 'GdpPerCapita', 'PPP', 'ObesityIndex','InsuranceType')
head(df)

```


```{r}
customColors <- c("#OB0033", "#003B36", "#BCB8B1", "#D95D39", "#0072B2")
```


```{r}
myPlot <- ggplot(df, aes(PPP, ExpectedHealthyYears)) +
  # Adding the regression fit before the points make sure the line stays behind the points.
  geom_smooth(
    # aes(color = "y ~ log(x)", fill = "y ~ log(x)"),
    method = "lm", 
    formula = y~log(x), 
    color="black", 
    se = FALSE
  

  ) +
  geom_point(
    aes(color = InsuranceType, fill = InsuranceType, size=ObesityIndex),
     alpha = 1.0, 
    shape = 21
  ) +
scale_color_manual(
  name = NULL,
  values = c("black","black", "black", "black", "black", "black")
) +
scale_fill_manual(
  name = NULL,
  values = c("darkred", "darkorange", "darkblue", "darkgreen", "purple", "black")

 ) + 
  
   scale_x_continuous(
    name = "PPP per Capita"
  ) +
 
  scale_y_continuous(
    name = "Expected Healthy Years of Life at Birth"

  ) +
  annotate('text', x = 10100, y = 65.2, label = 'U.S.A.') +
  ggtitle("How Financially Ineffective is the U.S. Healthcare System?") +
guides(color = guide_legend(override.aes = list(size=5)))

myPlot
```



